project:
  type: website
  output-dir: docs

website:
  title: "Biostatistics Consulting"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - href: signup.qmd
  #       text: Sign Up
  #     - href: reflections.qmd
  #       text: Student Reflections


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
