---
title: "Biostatistics Consulting"
---

- PH 246
- Fall 2025
- Tuesdays, 2-3 pm (plus your 2h/wk consultations)
- BWW 1206
- 1 unit, S/U
- Prof. Alejandro Schuler (`alejandro.schuler@berkeley.edu` | [bio](https://ctml.berkeley.edu/people/alejandro-schuler-phd))

# Goals

The goal of this course is to give biostatistics graduate students structured opportunities to work with domain researchers, hone consulting skills, and receive feedback. Consulting is a core ability necessary for success in both academia and industry that we explicitly emphasize in our training program. While student expertise may sometimes not be sufficient to fully resolve the problems raised by collaborators, it is precisely the process of encountering these new problems or of translating unfamiliar scenarios to formal statistical terms that cultivates growth and statistical maturity. 

Simultaneously, this course aims to provide a free quantitative consulting service accessible to the BPH community, e.g. MPH students working on their capstone projects.

# Prerequisites

This course is accessible to anyone with a strong foundation in statistics and is designed to be taken by 2nd-year master's students and 2nd+ year PhD students in biostatistics. However, students in other programs such as epidemiology, computational precision health, or health policy and management are certainly welcome and contribute to the diversity and strength of the course. We specifically require:

- probability theory (STAT 201A or equivalent)
- statistics (STAT 201B or equivalent)
- linear models (STAT 230A or equivalent)
- programming (STAT 234 or equivalent)

Additional courses such as causal inference (PH 252A) or longitudinal data analysis (PH 242C) are very helpful but not required.

# Materials, Texts, and Communication

The course website is [alejandroschuler.github.io/stats-consult](https://alejandroschuler.github.io/stats-consult/). You can find this syllabus there. There are no other required course materials, readings, or texts. All communication will be through email.

# First Week To-Dos:

- [Schedule consult hours](https://docs.google.com/spreadsheets/d/1EBAuHdpTIGzYyFylqY08Kx4ZucXMAg8lz8Q9be_5qSs/edit?gid=0#gid=0) (details below)
    - [Add the Biostat Consult gCalendar to your own Berkeley gCalendar](https://calendar.google.com/calendar/u/1?cid=Y19iZjI5ZmRjZjFkZWEwNjRhNTc2MTNjNmI0MjRkNWZhNzcwMmRmN2Y4ODUyMzgxZTI3MjBjODhlOThjM2I3MGM4QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20)
- [Pick your Presentation Days](https://docs.google.com/spreadsheets/d/1qf1MwXqOTojfCxPWmM3bJGfXAf9HTHjKZZgyn-ZaN9g/edit?usp=sharing)


# Format and Requirements

The course consists of one hour a week of “lecture” and two hours a week of consulting time (starting on week 2). 

## Lecture and Readings

In the first few weeks of the course we will use our joint meeting time for some expository lectures on how to approach statistical consultation. After this our meeting times will be used for guest lectures so you can see how consulting is done in the real world (industry and academia) and for student presentations. You are each expected to give a 20 minute presentation about one of your consultations once during the semester (the rest of the class time on that day will be spent discussing the consult you presented).

| Week | Topic | Readings |
| --- | --- | --- |
| 9/2 | [Statistical Consulting](question.html) | [I wish I had known...](https://github.com/alejandroschuler/stats-consult/blob/main/dialogues/Starter%20Guide%20to%20Academic%20Consulting.pdf) | 
| 9/9 | [Consult Walkthrough](https://youtu.be/I6I63ziLHD4) | [demo 1](https://github.com/alejandroschuler/stats-consult/blob/main/dialogues/AK_dialogue.pdf), [demo 2](https://github.com/alejandroschuler/stats-consult/blob/main/dialogues/sky_consult_dialogue.pdf) |
| 9/16 | First Consults: Group Discussion | [GEE Review](https://www.jstor.org/stable/pdf/2669353.pdf?casa_token=zja7DZxO2jcAAAAA:2A2IlZyjwwP_0sv1WUnJSCsO74lM9186UF560rqR-0zHWozjs6egI_qLilkrYdltmslgoGesCnomTY2OSYR3WTn0vA5uh8uWz1jiwM5zucpNTtfwkg), [To GEE or not to GEE?](https://sci-hub.ru/https://pubmed.ncbi.nlm.nih.gov/20220526/)|
| 9/23 | Guest Lecture: [Arman Sabbaghi](https://www.linkedin.com/in/arman-sabbaghi-51218391/) ||
| 9/30 | Student Presentations ||
| 10/7 | Guest Lecture: [Stacey Alexeeff](https://divisionofresearch.kaiserpermanente.org/researchers/alexeeff-stacey/) ||
| 10/14 | Guest Lecture: [Richard Zink](https://www.linkedin.com/in/richard-c-zink/) ||
| 10/21 | Student Presentations ||
| 10/28 | Student Presentations ||
| 11/4 | Student Presentations ||
| 11/18 | Guest Lecture: [Shira Mitchell](https://shiraamitchell.github.io/) ||
| 11/25 | Student Presentations ||
| 12/2 | Student Presentations ||
| 12/9 | Student Presentations ||

## Consults

During your two hours of consulting time(s), you and one other student will sit in a room and take consults from clients. Clients may either schedule in advance or drop-in and it’s up to you how to manage that time. Clients will come with statistical questions related to their projects and it is your job to try and help them make progress by clarifying/formalizing their questions and finding appropriate resources for them. Your individual consulting times and locations will be scheduled in the first week of the course using this [link](https://docs.google.com/spreadsheets/d/1EBAuHdpTIGzYyFylqY08Kx4ZucXMAg8lz8Q9be_5qSs/edit?gid=0#gid=0). 

Clients will be able to schedule an appointment using this [link](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ0kwMTIzYz7yNNzm7a8EIkopFfkg2Cl1ZC26UwMQF6BrzZdPt2iFWRp3R3kI8sfAWsYOC_taGM6). Note that all appointments are up to an hour and begin on the hour, contrary to what the scheduling link says. For example, folks scheduled at 9:30 should show up at 9 and you can begin helping them immediately. Google calendar does not allow scheduling multiple appointments concurrently, but for most hours we actually have two consultants present. You can view the appointments by [adding the Biostat Consult gCalendar to your own Berkeley gCalendar by clicking this link](https://calendar.google.com/calendar/u/1?cid=Y19iZjI5ZmRjZjFkZWEwNjRhNTc2MTNjNmI0MjRkNWZhNzcwMmRmN2Y4ODUyMzgxZTI3MjBjODhlOThjM2I3MGM4QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20). 

Before showing up to your consult hours, look at the [appointment schedule](https://calendar.google.com/calendar/u/1?cid=Y19iZjI5ZmRjZjFkZWEwNjRhNTc2MTNjNmI0MjRkNWZhNzcwMmRmN2Y4ODUyMzgxZTI3MjBjODhlOThjM2I3MGM4QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20). Briefly review the questions and methods mentioned. During consults, first attend to people with appointments and take walk-ins after. Time management is up to you. If it's not too busy you can work together with your co-consultant.

The consults are meant to be open-ended. You are welcome to engage deeply (e.g. up to and including writing some R code or doing a simple proof) but it’s not your responsibility to do someone else’s project, especially if that means you are ignoring other clients. You are free to do any follow-up work you like with clients but if you have one client that is repeatedly taking up a lot of time during the consult you can take another consult first

The service is not meant to be a tutoring service: you should turn away students who want help on their homework. Also please prioritize questions with statistical content. If the question is purely about coding (data cleaning, visualization) you may refer the client to the D-lab consulting services. However most people who think they just have coding questions actually benefit immensely from consulting about their statistical analyses.

## Guest Lectures

I've invited a few presenters with a lot of consulting experience across different parts of industry and academia to come give their perspectives to the class. Some may have some formal presentation but I will also be asking them the following questions:

- what's your general approach to a consult: how do you elucidate/formalize the research question?
- methods: how do you match methods to the question? What goes into that decision (e.g. accessibility, ease of use, correctness of approach, time)? How much and what kind of research do you do to find answers?
- give us an example consult or walk-through of the whole process
- logistics: how do you find clients, set up consults, and have a structure where people can engage you?
- new problems: what's the relationship between independent methods work and consulting for a practicing statistician?
- sustainability : how do statistical consultants get paid and have their work recognized?
- relationship building: how do you manage mutually-beneficial long-term engagements?
- lessons: how has your approach to consulting changed over time and why?

You should look up our speakers and come prepared with your own questions as well.

## Student Presentations

The point of the presentations is to reflect on a (some) consult(s) of your choice. You will present twice in the semester and each presentation should be about 20m long with plenty of time for questions and discussion. You can [sign up here](https://docs.google.com/spreadsheets/d/1qf1MwXqOTojfCxPWmM3bJGfXAf9HTHjKZZgyn-ZaN9g/edit?usp=sharing) to pick what days you want to present

Your presentation should address:

- What was the research question? What data did the client have?
- How did you statistically formalize/refine the question? Any alternatives?
- What assumptions were required and how did you assess them?
- What analysis did you suggest and why? What alternatives?
- What did you have to research or teach yourself?
- Did you have to teach them any concepts? Which? Why? How did you do it?
- How did you interpret the results or discuss how you would interpret them?
- How did you make the client comfortable talking to you?
- Overall, what was hard and what was easy? What did you take away?

Each of your presentations will be graded pass/fail. A pass is acheived by any substantive commentary on 4+ of the above topics. 

## Final Assessment: Consulting Guide

At the end of the course you must write a "consulting guide": all the advice you would give to a student running their first consult next semester (i.e. what you wish *you* had known before starting the course). The guide should:

- be roughly 2-4 pages in length 
- address 4+ of the themes discussed in the student presentations above
- use at least two concrete examples from your consulting experience to demonstrate your advice
- make some distinction between between what you think are important and unimportant skills or techniques
- compare/contrast your attitudes and perspectives on statistical consulting before and after the course

Guides are graded pass/not pass. Any guide that meets those criteria and is turned in by the deadline of **Dec. 16th** will receive a pass grade.

# Grading and Policies

Grading for the course is S/U. To pass the course you must get passing grades on all assignments (2 presentations and consulting guide), have an 80%+ attendance record for lecture, and no unexcused absences for your consulting hours (barring emergencies or unforseeable circumstance). If you have any issues preventing you from attending or participating please let me know as soon as possible. Also know that you are welcome to trade or cover each others' consulting hours.

Descriptions of and relevant campus links to SPH school wide course policies on Disability Support Services, Accommodation of Religions Creed, Course Evaluations, Academic Integrity can be found at: https://berkeley.box.com/s/knh3rbk9ikgvmca4ymy93msgj9bkebq5